/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Add_new_Branch_Entery_from.java
 *
 * Created on May 16, 2012, 1:00:30 PM
 */

/**
 *
 * @author Amresh
 */
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class Add_new_Branch_Entery_from extends javax.swing.JFrame {
        Connection con;
	Statement st;
	ResultSet rs;
	ResultSetMetaData rmeta;


    /** Creates new form Add_new_Branch_Entery_from */
    public Add_new_Branch_Entery_from() {
        initComponents();
        cb1.addItem("YES");
        cb1.addItem("NO");
  
    }
    public boolean setconn(String ds,String user,String pwd)
{
	try{

	Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
	String url="jdbc:odbc:"+ds;
	con=DriverManager.getConnection(url,user,pwd);
	return(true);

	}
catch(Exception e)
{
	System.out.print(e.getMessage());
	 return(false);
}
}//close of conn()
     public void mySelect(String table)
{
    try
    {
        st=con.createStatement();
        String sql="SELECT * From "+table;
        rs=st.executeQuery(sql);
        //myDisplayResult(result);
       // rs.next();
        //t1.setText(rs.getString(1));
        //p1.setText(rs.getString(2));


    }
    catch(Exception e)
    {
        System.out.println("Error:"+e.getMessage());

    }



}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t6 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t10 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BRANCH ENTRY");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("OUR NEW  BRANCH ENTERY FORM");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 30, 320, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HDWallpapers (48).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 4, 920, 50);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel3.setText("Branch Name");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 190, 100, 17);

        t1.setName("t1"); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(130, 30, 180, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Address");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 60, 60, 17);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        t2.setColumns(20);
        t2.setRows(5);
        t2.setName("t2"); // NOI18N
        jScrollPane1.setViewportView(t2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 60, 180, 96);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText("Dist");
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 170, 27, 17);

        t3.setName("t3"); // NOI18N
        jPanel1.add(t3);
        t3.setBounds(140, 160, 180, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel6.setText("Branch code");
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 30, 90, 17);

        t4.setName("t4"); // NOI18N
        jPanel1.add(t4);
        t4.setBounds(140, 190, 180, 20);

        t5.setName("t5"); // NOI18N
        jPanel1.add(t5);
        t5.setBounds(140, 220, 180, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setText("Total member");
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 220, 100, 14);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel8.setText("Secqurrty name");
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 60, 120, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel9.setText("Persident name");
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(530, 90, 120, 17);

        t8.setName("t8"); // NOI18N
        jPanel1.add(t8);
        t8.setBounds(700, 60, 170, 20);

        t7.setName("t7"); // NOI18N
        jPanel1.add(t7);
        t7.setBounds(700, 30, 170, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel10.setText("Enter Total Member Name");
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(330, 30, 190, 17);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        t6.setColumns(20);
        t6.setRows(5);
        t6.setName("t6"); // NOI18N
        jScrollPane2.setViewportView(t6);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(340, 60, 166, 180);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel11.setText("Branch Phon Number");
        jLabel11.setName("jLabel11"); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(530, 30, 160, 17);

        t9.setName("t9"); // NOI18N
        jPanel1.add(t9);
        t9.setBounds(700, 90, 170, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel12.setText("Issue by Rajesh Kumar Singh");
        jLabel12.setName("jLabel12"); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(530, 120, 210, 17);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel13.setText("ABOUT");
        jLabel13.setName("jLabel13"); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(530, 150, 60, 20);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        t10.setColumns(20);
        t10.setRows(5);
        t10.setName("t10"); // NOI18N
        jScrollPane3.setViewportView(t10);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(590, 150, 290, 96);

        jButton1.setText("SUBMIT");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 263, 80, 40);

        jButton2.setText("EXIT");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 253, 100, 50);

        cb1.setName("cb1"); // NOI18N
        jPanel1.add(cb1);
        cb1.setBounds(740, 120, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 90, 920, 330);

        jLabel14.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Branch Must Be Issue By  The Onwer Rajesh Kumar Singh secquerty of Main Branch Katihar");
        jLabel14.setName("jLabel14"); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 60, 810, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-931)/2, (screenSize.height-454)/2, 931, 454);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
             String bcode =t1.getText();
             String add =t2.getText();
             String Dist =t3.getText();
             String bname =t4.getText();
             String tmember =t5.getText();
             String tmname =t6.getText();
             String bpnumber =t7.getText();
             String sname =t8.getText();
             String pname =t9.getText();
             String About =t10.getText();
             String issue=cb1.getSelectedItem().toString();

        con.setAutoCommit(false);
        PreparedStatement ps=con.prepareStatement("INSERT INTO  Newbranch VALUES(?,?,?,?,?,?,?,?,?,?,?)");
        ps.setString(1,bcode);
        ps.setString(2,add);
        ps.setString(3,Dist);
        ps.setString(4,bname);
        ps.setString(5,tmember);
        ps.setString(6,tmname);
        ps.setString(7,bpnumber);
        ps.setString(8,sname);
        ps.setString(9,pname);
        ps.setString(10,issue);
         ps.setString(11,About);


        ps.addBatch();
        int r[]=ps.executeBatch();
        con.commit();
        JOptionPane.showMessageDialog(this,"Record Saved Successfully");



    }//GEN-LAST:event_jButton1ActionPerformed
catch(Exception e)
{
	JOptionPane.showMessageDialog(this,e.getMessage());
	// return(false);
}
}// conn()

        private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_t1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
            setVisible(false);
        }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_new_Branch_Entery_from().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextArea t10;
    private javax.swing.JTextArea t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextArea t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables

}
