/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Child_record.java
 *
 * Created on May 17, 2012, 12:10:03 PM
 */

/**
 *
 * @author Amresh
 */
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class Child_record extends javax.swing.JFrame {
        Connection con;
	Statement st;
	ResultSet rs;
	ResultSetMetaData rmeta;


    /** Creates new form Child_record */
    public Child_record() {
        initComponents();
    }
    public boolean setconn(String ds,String user,String pwd)
{
	try{

	Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
	String url="jdbc:odbc:"+ds;
	con=DriverManager.getConnection(url,user,pwd);
	return(true);

	}
catch(Exception e)
{
	System.out.print(e.getMessage());
	 return(false);
}
}//close of conn()
     public void mySelect(String table)
{
    try
    {
        st=con.createStatement();
        String sql="SELECT * From "+table;
        rs=st.executeQuery(sql);
        //myDisplayResult(result);
       // rs.next();
        //t1.setText(rs.getString(1));
        //p1.setText(rs.getString(2));


    }
    catch(Exception e)
    {
        System.out.println("Error:"+e.getMessage());

    }



}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t6 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t8 = new javax.swing.JTextArea();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");
        jTextField3.setName("jTextField3"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Child record");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel1.setText("Child Record form");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 170, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HDWallpapers (95).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1380, 80);

        jPanel1.setBackground(new java.awt.Color(240, 139, 172));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel3.setText("Name of Child");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 50, 100, 17);

        t1.setName("t1"); // NOI18N
        jPanel1.add(t1);
        t1.setBounds(150, 50, 170, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setText("Name of broker");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 80, 110, 20);

        t2.setName("t2"); // NOI18N
        jPanel1.add(t2);
        t2.setBounds(150, 80, 170, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText("Broker Address");
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 110, 110, 17);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        t3.setColumns(20);
        t3.setRows(5);
        t3.setName("t3"); // NOI18N
        jScrollPane1.setViewportView(t3);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 110, 170, 96);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel6.setText("Date of get");
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 210, 80, 17);

        t4.setName("t4"); // NOI18N
        jPanel1.add(t4);
        t4.setBounds(150, 210, 170, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setText("Abhilasha hand Over With");
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 250, 190, 17);

        t5.setName("t5"); // NOI18N
        jPanel1.add(t5);
        t5.setBounds(230, 250, 90, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel8.setText("Adress to which gat Abhilasha Child");
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(340, 50, 250, 17);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        t6.setColumns(20);
        t6.setRows(5);
        t6.setName("t6"); // NOI18N
        jScrollPane2.setViewportView(t6);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(340, 70, 260, 96);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel9.setText("Abhilasha Member name to gat child");
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(340, 180, 260, 17);

        t7.setName("t7"); // NOI18N
        jPanel1.add(t7);
        t7.setBounds(340, 210, 260, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel10.setText("About");
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(350, 250, 50, 17);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        t8.setColumns(20);
        t8.setRows(5);
        t8.setName("t8"); // NOI18N
        jScrollPane3.setViewportView(t8);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(400, 240, 200, 96);

        jTextField7.setText("             Photo");
        jTextField7.setName("jTextField7"); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(690, 50, 110, 110);

        jButton1.setText("Add");
        jButton1.setName("jButton1"); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(710, 170, 73, 23);

        jButton2.setText("Submit");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 373, 100, 40);

        jButton3.setText("Exit");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(790, 370, 110, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 100, 1400, 740);

        jLabel11.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("ABHILASHA PARIWAR SWYEMSEVI SANSTHA");
        jLabel11.setName("jLabel11"); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 80, 430, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-953)/2, (screenSize.height-567)/2, 953, 567);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
             String name =t1.getText();
             String nb =t2.getText();
             String ba =t3.getText();
             String date =t4.getText();
             String ahow =t5.getText();
             String add =t6.getText();
             String amn =t7.getText();
             String about =t8.getText();



        con.setAutoCommit(false);
        PreparedStatement ps=con.prepareStatement("INSERT INTO   child_record VALUES(?,?,?,?,?,?,?,?)");
        ps.setString(1,name);
        ps.setString(2,nb);
        ps.setString(3,ba);
        ps.setString(4,date);
        ps.setString(5,ahow);
        ps.setString(6,add);
        ps.setString(7,amn);
         ps.setString(8,about);


        ps.addBatch();
        int r[]=ps.executeBatch();
        con.commit();
        JOptionPane.showMessageDialog(this,"Record Saved Successfully");



    }//GEN-LAST:event_jButton2ActionPerformed
catch(Exception e)
{
	JOptionPane.showMessageDialog(this,e.getMessage());
	 //return(false);
}
}

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // TODO add your handling code here:
            setVisible(false);
        }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Child_record().setVisible(true);
            }
            });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextArea t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextArea t8;
    // End of variables declaration//GEN-END:variables


}
