/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ID_CARD.java
 *
 * Created on May 15, 2012, 4:51:34 PM
 */

/**
 *
 * @author Amresh
 */
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class ID_CARD extends javax.swing.JFrame {
         Connection con;
	Statement st;
	ResultSet rs;
	ResultSetMetaData rmeta;


    /** Creates new form ID_CARD */
    public ID_CARD() {
        initComponents();
        cb1.addItem("Male");
        cb1.addItem("FeMale");

    }
    public boolean setconn(String ds,String user,String pwd)
{
	try{

	Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
	String url="jdbc:odbc:"+ds;
	con=DriverManager.getConnection(url,user,pwd);
	return(true);

	}
catch(Exception e)
{
	System.out.print(e.getMessage());
	 return(false);
}
}//close of conn()
     public void mySelect(String table)
{
    try
    {
        st=con.createStatement();
        String sql="SELECT * From "+table;
        rs=st.executeQuery(sql);
        //myDisplayResult(result);
       // rs.next();
        //t1.setText(rs.getString(1));
        //p1.setText(rs.getString(2));


    }
    catch(Exception e)
    {
        System.out.println("Error:"+e.getMessage());

    }



}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        t5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ISSUE ID CARD BY ABHILASHA");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel3.setText("Name");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 70, 50, 17);

        t1.setName("t1"); // NOI18N
        jPanel1.add(t1);
        t1.setBounds(150, 40, 150, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setText("Member Id");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 40, 80, 17);

        t2.setName("t2"); // NOI18N
        jPanel1.add(t2);
        t2.setBounds(150, 70, 150, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText("Address");
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 110, 80, 20);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        t3.setColumns(20);
        t3.setRows(5);
        t3.setName("t3"); // NOI18N
        jScrollPane1.setViewportView(t3);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 110, 160, 100);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel6.setText("Sex");
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 214, 40, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setText("Post");
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(74, 260, 40, 20);

        t4.setName("t4"); // NOI18N
        jPanel1.add(t4);
        t4.setBounds(160, 260, 150, 20);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(510, 50, 150, 120);

        jButton1.setText("Add photo");
        jButton1.setName("jButton1"); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(540, 180, 90, 23);

        b3.setText("cancel");
        b3.setName("b3"); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(620, 450, 80, 23);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel8.setText("issue Date");
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 300, 80, 17);

        cb1.setName("cb1"); // NOI18N
        jPanel1.add(cb1);
        cb1.setBounds(160, 220, 150, 20);

        jButton2.setText("Ok");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 450, 80, 23);

        t5.setName("t5"); // NOI18N
        jPanel1.add(t5);
        t5.setBounds(160, 290, 150, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 100, 790, 680);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18));
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText(" ID card issue by  Abhilasha");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 30, 310, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HDWallpapers (22).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1380, 80);

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 18));
        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setText("ABHILASHA PARIWAR SWYEMSEVI SANSTHA");
        jLabel9.setName("jLabel9"); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 80, 400, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-805)/2, (screenSize.height-631)/2, 805, 631);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try
      {// TODO add your handling code here:
        String memberid =t1.getText();
        String name =t2.getText();
         String Add =t3.getText();
         String sex=cb1.getSelectedItem().toString();
          String post =t4.getText();
        String idate=t5.getText();

        con.setAutoCommit(false);
        PreparedStatement ps=con.prepareStatement("INSERT INTO id_card_entery VALUES(?,?,?,?,?,?)");
      
        ps.setString(1,memberid);
        ps.setString(2,name);
        ps.setString(3,Add);
        ps.setString(4,sex);
        ps.setString(5,post);
        ps.setString(6,idate);
      
        ps.addBatch();
        int r[]=ps.executeBatch();
        con.commit();
         JOptionPane.showMessageDialog(this,"Record Saved Successfully");

    }//GEN-LAST:event_jButton2ActionPerformed
 catch(Exception e)
    {

    }
    }

      private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
          // TODO add your handling code here:
              setVisible(false);
      }//GEN-LAST:event_b3ActionPerformed
   
      /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ID_CARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3;
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables

}
