/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Lic_entery.java
 *
 * Created on May 16, 2012, 8:39:43 AM
 */

/**
 *
 * @author Amresh
 */
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class Lic_entery extends javax.swing.JFrame {
        Connection con;
	Statement st;
	ResultSet rs;
	ResultSetMetaData rmeta;


    /** Creates new form Lic_entery */
    public Lic_entery() {
        initComponents();
         cb1.addItem("Jivan mangal");
        cb1.addItem("Jivae Madhur");

    }
    public boolean setconn(String ds,String user,String pwd)
{
	try{

	Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
	String url="jdbc:odbc:"+ds;
	con=DriverManager.getConnection(url,user,pwd);
	return(true);

	}
catch(Exception e)
{
	System.out.print(e.getMessage());
	 return(false);
}
    }
     public void mySelect(String table)
{
    try
    {
        st=con.createStatement();
        String sql="SELECT * From "+table;
        rs=st.executeQuery(sql);
        //myDisplayResult(result);
       // rs.next();
        //t1.setText(rs.getString(1));
        //p1.setText(rs.getString(2));


    }
    catch(Exception e)
    {
        System.out.println("Error:"+e.getMessage());

    }



}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lic Recored Entery By Abhilasha Pariwar");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lic Recored Entery By Abhilasha Pariwar");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 10, 360, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HDWallpapers (55).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 70);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel3.setText("Name");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 40, 40, 20);

        t1.setName("t1"); // NOI18N
        jPanel1.add(t1);
        t1.setBounds(140, 40, 150, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setText("Policy Type");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 130, 80, 17);

        cb1.setName("cb1"); // NOI18N
        jPanel1.add(cb1);
        cb1.setBounds(140, 130, 150, 20);

        t2.setName("t2"); // NOI18N
        jPanel1.add(t2);
        t2.setBounds(140, 70, 150, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel6.setText("No of Instalment");
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 70, 120, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setText("Policy no");
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(22, 100, 70, 17);

        t5.setName("t5"); // NOI18N
        jPanel1.add(t5);
        t5.setBounds(430, 70, 130, 20);

        t3.setName("t3"); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t3FocusLost(evt);
            }
        });
        jPanel1.add(t3);
        t3.setBounds(140, 100, 150, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel9.setText("Date of End Policy");
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(320, 100, 140, 10);

        t6.setName("t6"); // NOI18N
        jPanel1.add(t6);
        t6.setBounds(490, 100, 70, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel10.setText("Plan Year");
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(320, 70, 70, 17);

        t4.setName("t4"); // NOI18N
        jPanel1.add(t4);
        t4.setBounds(430, 40, 130, 20);

        t7.setName("t7"); // NOI18N
        jPanel1.add(t7);
        t7.setBounds(490, 130, 70, 20);

        jButton1.setText("Entry");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 183, 100, 30);

        jButton2.setText("Exit");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(620, 180, 90, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel12.setText("Total perumem Amount");
        jLabel12.setName("jLabel12"); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(320, 130, 170, 17);

        t8.setName("t8"); // NOI18N
        jPanel1.add(t8);
        t8.setBounds(670, 40, 70, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel13.setText("Paid Amount");
        jLabel13.setName("jLabel13"); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(570, 40, 90, 17);

        t9.setName("t9"); // NOI18N
        jPanel1.add(t9);
        t9.setBounds(670, 70, 70, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel14.setText("Due Amount");
        jLabel14.setName("jLabel14"); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(570, 70, 90, 17);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel15.setText("paid");
        jLabel15.setName("jLabel15"); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(320, 40, 30, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 100, 810, 260);

        jLabel11.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel11.setText("This Project Handel By Abhilasha pariwar swyemsevi  sanstha  Katihar Bihar");
        jLabel11.setName("jLabel11"); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 80, 670, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-822)/2, (screenSize.height-398)/2, 822, 398);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
             String name =t1.getText();
             String noinst =t2.getText();
             String p_no =t3.getText();
             String p_type=cb1.getSelectedItem().toString();
             String paid =t4.getText();
             String pl_year =t5.getText();
             String dateend =t6.getText();
             String tpamount =t7.getText();
             String p_amount =t8.getText();
             String due =t9.getText();


        con.setAutoCommit(false);
        PreparedStatement ps=con.prepareStatement("INSERT INTO   lic_entery VALUES(?,?,?,?,?,?,?,?,?,?)");
        ps.setString(1,name);
        ps.setString(2,noinst);
        ps.setString(3,p_no);
        ps.setString(4,p_type);
        ps.setString(5,paid);
        ps.setString(6,pl_year);
        ps.setString(7,dateend);
        ps.setString(8,tpamount);
        ps.setString(9,p_amount);
        ps.setString(10,due);
        


        ps.addBatch();
        int r[]=ps.executeBatch();
        con.commit();
        JOptionPane.showMessageDialog(this,"Record Saved Successfully");


    }//GEN-LAST:event_jButton1ActionPerformed
catch(Exception e)
{
	System.out.print(e.getMessage());
	// return(false);
}
    }
    private void t3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t3FocusLost

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lic_entery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables

}
