/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * new_member_entery.java
 *
 * Created on May 15, 2012, 2:03:37 AM
 */

/**
 *
 * @author Amresh
 */
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class new_member_entery extends javax.swing.JFrame {
        Connection con;
	Statement st;
	ResultSet rs;
	ResultSetMetaData rmeta;


    /** Creates new form new_member_entery */
    public new_member_entery() {

       initComponents();

       cb1.addItem("Inter");
        cb1.addItem("Graduation");
        cb1.addItem("Post Graduation");
        cb1.addItem("Engineer");
        cb1.addItem("PHD");
        cb1.addItem("Software Engineer");

        cb2.addItem("2001");
        cb2.addItem("2002");
        cb2.addItem("2003");
        cb2.addItem("2004");
        cb2.addItem("2005");
        cb2.addItem("2006");
        cb2.addItem("2007");
        cb2.addItem("2008");
        cb2.addItem("2009");
        cb2.addItem("2010");
        cb2.addItem("2011");
        cb2.addItem("2012");

        cb3.addItem("President");
        cb3.addItem("Secretary");
        cb3.addItem("Accountant");
        cb3.addItem("General Member");

        cb4.addItem("Male");
        cb4.addItem("FeMale");

        cb5.addItem("Married");
        cb5.addItem("UnMarried");

        

        
    }
     public boolean setconn(String ds,String user,String pwd)
    {
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            String url="jdbc:odbc:"+ds;
            con=DriverManager.getConnection(url,user,pwd);
            return(true);
        }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
            return(false);
        }
    }
      public void mySelect(String table)
{
    try
    {
        st=con.createStatement();
        String sql="SELECT * From "+table;
        rs=st.executeQuery(sql);
        //myDisplayResult(result);
       // rs.next();
        //t1.setText(rs.getString(1));
        //p1.setText(rs.getString(2));


    }
    catch(Exception e)
    {
        System.out.println("Error:"+e.getMessage());

    }



}
   public void display()
{
	try{
		st=con.createStatement();
		String sql="SELECT *from  STUDENT";
		rs=st.executeQuery(sql);
		rs.next();

	//t1.setText(rs.getString(1));
	//t2.setText(rs.getString(2));
	//t3.setText(rs.getString(3));
	//t4.setText(rs.getString(4));
	}
catch(Exception e)
{

}
   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t8 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cb2 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        cb3 = new javax.swing.JComboBox();
        cb4 = new javax.swing.JComboBox();
        cb5 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Member Entery form");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Vani", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Abhilasha Member Entry From");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 400, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HDWallpapers (98).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1050, 90);

        t1.setBackground(new java.awt.Color(255, 204, 204));
        t1.setName("t1"); // NOI18N
        t1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel3.setText("Name");
        jLabel3.setName("jLabel3"); // NOI18N
        t1.add(jLabel3);
        jLabel3.setBounds(40, 40, 40, 20);

        t2.setName("t2"); // NOI18N
        t1.add(t2);
        t2.setBounds(110, 40, 190, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setText("  Address");
        jLabel4.setName("jLabel4"); // NOI18N
        t1.add(jLabel4);
        jLabel4.setBounds(30, 70, 66, 20);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        t3.setColumns(20);
        t3.setRows(5);
        t3.setName("t3"); // NOI18N
        jScrollPane1.setViewportView(t3);

        t1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 80, 190, 96);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText("New ID");
        jLabel5.setName("jLabel5"); // NOI18N
        t1.add(jLabel5);
        jLabel5.setBounds(40, 10, 60, 20);

        tid.setName("tid"); // NOI18N
        t1.add(tid);
        tid.setBounds(110, 10, 190, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel6.setText("Post");
        jLabel6.setName("jLabel6"); // NOI18N
        t1.add(jLabel6);
        jLabel6.setBounds(320, 20, 40, 10);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setText("Sex");
        jLabel7.setName("jLabel7"); // NOI18N
        t1.add(jLabel7);
        jLabel7.setBounds(320, 40, 30, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Qualification");
        jLabel8.setName("jLabel8"); // NOI18N
        t1.add(jLabel8);
        jLabel8.setBounds(10, 300, 100, 20);

        cb1.setName("cb1"); // NOI18N
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        t1.add(cb1);
        cb1.setBounds(130, 300, 170, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel9.setText("Date");
        jLabel9.setName("jLabel9"); // NOI18N
        t1.add(jLabel9);
        jLabel9.setBounds(320, 110, 40, 17);

        t7.setName("t7"); // NOI18N
        t1.add(t7);
        t7.setBounds(380, 150, 140, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Year");
        jLabel10.setName("jLabel10"); // NOI18N
        t1.add(jLabel10);
        jLabel10.setBounds(10, 330, 40, 20);

        t6.setName("t6"); // NOI18N
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        t1.add(t6);
        t6.setBounds(380, 110, 150, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Parmanent Add");
        jLabel12.setName("jLabel12"); // NOI18N
        t1.add(jLabel12);
        jLabel12.setBounds(10, 180, 110, 20);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        t4.setColumns(20);
        t4.setRows(5);
        t4.setName("t4"); // NOI18N
        jScrollPane2.setViewportView(t4);

        t1.add(jScrollPane2);
        jScrollPane2.setBounds(110, 200, 190, 96);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel13.setText("maried");
        jLabel13.setName("jLabel13"); // NOI18N
        t1.add(jLabel13);
        jLabel13.setBounds(320, 80, 50, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel14.setText("Hobbey");
        jLabel14.setName("jLabel14"); // NOI18N
        t1.add(jLabel14);
        jLabel14.setBounds(320, 150, 60, 17);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        t8.setColumns(20);
        t8.setRows(5);
        t8.setName("t8"); // NOI18N
        jScrollPane3.setViewportView(t8);

        t1.add(jScrollPane3);
        jScrollPane3.setBounds(320, 200, 370, 96);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel15.setText("About");
        jLabel15.setName("jLabel15"); // NOI18N
        t1.add(jLabel15);
        jLabel15.setBounds(320, 180, 60, 17);

        jButton1.setText("Submit");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        t1.add(jButton1);
        jButton1.setBounds(350, 390, 90, 30);

        jButton2.setText("Cancel");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        t1.add(jButton2);
        jButton2.setBounds(515, 390, 80, 30);

        jTextField7.setText("             Photo");
        jTextField7.setName("jTextField7"); // NOI18N
        t1.add(jTextField7);
        jTextField7.setBounds(700, 30, 130, 110);

        jButton3.setText("Add Member image");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        t1.add(jButton3);
        jButton3.setBounds(700, 150, 140, 23);

        cb2.setName("cb2"); // NOI18N
        t1.add(cb2);
        cb2.setBounds(130, 330, 170, 20);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("city");
        jLabel17.setName("jLabel17"); // NOI18N
        t1.add(jLabel17);
        jLabel17.setBounds(10, 360, 30, 17);

        t5.setName("t5"); // NOI18N
        t1.add(t5);
        t5.setBounds(130, 360, 170, 20);

        cb3.setName("cb3"); // NOI18N
        t1.add(cb3);
        cb3.setBounds(380, 10, 130, 20);

        cb4.setName("cb4"); // NOI18N
        t1.add(cb4);
        cb4.setBounds(380, 40, 130, 20);

        cb5.setName("cb5"); // NOI18N
        t1.add(cb5);
        cb5.setBounds(380, 80, 130, 20);

        getContentPane().add(t1);
        t1.setBounds(0, 130, 1050, 570);

        jLabel16.setBackground(new java.awt.Color(255, 102, 102));
        jLabel16.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("ABHILASHA PARIWAR SWYEMSEVI SANSTHA MIRCHARBARI KATIHAR BIHAR");
        jLabel16.setName("jLabel16"); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(260, 100, 720, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1059)/2, (screenSize.height-697)/2, 1059, 697);
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        String NEW_ID =tid.getText();
        String name =t2.getText();
        String Add =t3.getText();
        String PAdd =t4.getText();
        String qual=cb1.getSelectedItem().toString();
        String year=cb2.getSelectedItem().toString();
        String post=cb3.getSelectedItem().toString();
        String sex=cb4.getSelectedItem().toString();
        String maried=cb5.getSelectedItem().toString();
        
        String city =t5.getText();
        String Date =t6.getText();
        String Hobby=t7.getText();
        String About =t8.getText();

        con.setAutoCommit(false);
        PreparedStatement ps=con.prepareStatement("INSERT INTO New_Member VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)");

        ps.setString(1,NEW_ID);
        ps.setString(2,name);
        ps.setString(3,Add);
        ps.setString(4,PAdd);
        ps.setString(5,qual);
        ps.setString(6,year);
        ps.setString(7,city);
        ps.setString(8,post);
        ps.setString(9,sex);
        ps.setString(10,maried);

        ps.setString(11,Date);
        ps.setString(12,Hobby);
        ps.setString(13,About);

        ps.addBatch();
        int r[]=ps.executeBatch();
        con.commit();
        JOptionPane.showMessageDialog(this,"Record Saved Successfully");
        

    }//GEN-LAST:event_jButton1ActionPerformed
catch(Exception e)
{
	JOptionPane.showMessageDialog(this,e);
	
}
    }
        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
            setVisible(false);
        }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_member_entery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JComboBox cb4;
    private javax.swing.JComboBox cb5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTextArea t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextArea t8;
    private javax.swing.JTextField tid;
    // End of variables declaration//GEN-END:variables

}
