/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * welcome_screen.java
 *
 * Created on May 14, 2012, 9:05:05 PM
 */

/**
 *
 * @author Amresh
 */
import javax.swing.*;

public class welcome_screen extends javax.swing.JFrame {

    /** Creates new form welcome_screen */
    public welcome_screen() {
        initComponents();
    }

    public void change()
    {
       

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();

        jLabel5.setBackground(new java.awt.Color(102, 51, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel5.setForeground(new java.awt.Color(0, 51, 0));
        jLabel5.setText("Please Wait........");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HDWallpapers (1).jpeg"))); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(welcome_screen.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("WELCOME TO ABHILASHA PARIWAR SWYEMSEVI SANSTHA");
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 110, 720, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("       MIRCHAIBARI KATIHAR BIHAR");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 140, 470, 40);

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        jPanel2.setForeground(new java.awt.Color(0, 102, 255));
        jPanel2.setEnabled(false);
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("NAME :ABHILASHA PARIWAR SWYEMSEVI SANSTHA");
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 240, 660, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HDWallpapers (13).JPG"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 960, 110);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("    THIS PROJECT IS FULLY LICENCED TO USE FOR NGO  ");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 180, 690, 40);

        jLabel8.setFont(new java.awt.Font("Modern No. 20", 1, 18));
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Please Wait.......");
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(640, 330, 150, 20);

        label1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        label1.setForeground(new java.awt.Color(102, 0, 0));
        label1.setName("label1"); // NOI18N
        label1.setText("DEVELOPED BY:---AMRESH KUMAR SINGH");
        jPanel1.add(label1);
        label1.setBounds(460, 380, 500, 32);

        label2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14));
        label2.setForeground(new java.awt.Color(204, 0, 51));
        label2.setName("label2"); // NOI18N
        label2.setText("ENROLLMENT No:--B-147225016");
        jPanel1.add(label2);
        label2.setBounds(670, 420, 270, 20);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 14));
        jButton1.setText("CLICK HERE TO COUNTINUE......");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 330, 290, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 960, 470);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-977)/2, (screenSize.height-506)/2, 977, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LOGIN_WINDOW lw=new LOGIN_WINDOW();
        lw.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome_screen().setVisible(true);
                new welcome_screen().change();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables

}
